clients = [
    {
        'active':True,
        'first_name':'George',
        'last_name':'Orwell',
        'address1':'Room 101',
        'address2':'525 Ferry Road',
        'town':'Edinburgh',
        'postcode':'EH5 2FF',
        'phone':'0131 555 9100',
        'gdpr_consent':'given_by_client',
        'health_status': 'self-isolating',
        'notes': 'Eric Arthur Blair (25 June 1903 – 21 January 1950), better known by his pen name George Orwell, was an English novelist and essayist, journalist and critic.',
        'schedule': {
            'status': 'active',
            'number_of_adults': 2,
            'number_of_children': 0,
            'allergies': 'Peanuts',
            'diabetic': False,
            'gluten_free': False,
            'dairy_free': False,
            'vegetarian': True,
            'vegan': True,
            'halal': False,
            'start_date': '2020-01-01',
            'end_date': '2020-12-31',
            'monday_delivery': True,
            'wednesday_delivery': True,
            'friday_delivery': True,
            'delivery_notes': 'Buzzer doesn\'t work. Call phone number.',
        }
    },
    {
        'active':True,
        'first_name':'Alan',
        'last_name':'Turing',
        'address1':'Chinese Room',
        'address2':'Bletchley Park',
        'town':'Edinburgh',
        'postcode':'EH10 1OI',
        'phone':'0131 555 9200',
        'gdpr_consent':'given_by_client',
        'health_status': 'self-isolating',
        'notes': 'Alan Mathison Turing OBE FRS was an English mathematician, computer scientist, logician, cryptanalyst, philosopher, and theoretical biologist.',
        'schedule': {
            'status': 'active',
            'number_of_adults': 2,
            'number_of_children': 3,
            'allergies': 'Lactose',
            'diabetic': False,
            'gluten_free': False,
            'dairy_free': True,
            'vegetarian': True,
            'vegan': True,
            'halal': False,
            'start_date': '2020-01-01',
            'end_date': '2020-12-31',
            'monday_delivery': True,
            'wednesday_delivery': True,
            'friday_delivery': True,
            'delivery_notes': 'If not in, leave food with neighbour.',
        }
    },
    {
        'active':True,
        'first_name':'Alfred',
        'last_name':'Hitchcock',
        'address1':'Flat 7',
        'address2':'Castle Terrace',
        'town':'Edinburgh',
        'postcode':'EH10 9FE',
        'phone':'0131 555 9300',
        'gdpr_consent':'given_by_client',
        'health_status': 'shielding',
        'notes': 'Sir Alfred Joseph Hitchcock, KBE (13 August 1899 – 29 April 1980) was an English film director and producer. He is one of the most influential and extensively studied filmmakers in the history of cinema.',
        'schedule': {
            'status': 'active',
            'number_of_adults': 1,
            'number_of_children': 2,
            'allergies': 'Shellfish',
            'diabetic': True,
            'gluten_free': False,
            'dairy_free': False,
            'vegetarian': False,
            'vegan': True,
            'halal': False,
            'start_date': '2020-01-01',
            'end_date': '2020-12-31',
            'monday_delivery': True,
            'wednesday_delivery': True,
            'friday_delivery': True,
            'delivery_notes': 'May take a while to reach the door',
        }
    },
    {
        'active':True,
        'first_name':'Orson',
        'last_name':'Welles',
        'address1':'1F2',
        'address2':'1 Grindlay Street',
        'town':'Edinburgh',
        'postcode':'EH1 2AB',
        'phone':'0131 555 9400',
        'gdpr_consent':'given_by_client',
        'health_status': 'shielding',
        'notes': 'George Orson Welles (May 6, 1915 – October 10, 1985) was an American actor, director, writer and producer who is remembered for his innovative work in radio, theatre and film. He is considered one of the greatest filmmakers of all time.',
        'schedule': {
            'status': 'active',
            'number_of_adults': 5,
            'number_of_children': 10,
            'allergies': '',
            'diabetic': True,
            'gluten_free': False,
            'dairy_free': False,
            'vegetarian': True,
            'vegan': True,
            'halal': False,
            'start_date': '2020-01-01',
            'end_date': '2020-12-31',
            'monday_delivery': True,
            'wednesday_delivery': True,
            'friday_delivery': True,
            'delivery_notes': None
        }
    },
    {
        'active':True,
        'first_name':'Django',
        'last_name':'Reinhardt',
        'address1':'Green Room',
        'address2':'The Jazz Bar',
        'town':'Edinburgh',
        'postcode':'EH2 3AB',
        'phone':'0131 555 9500',
        'gdpr_consent':'given_by_client',
        'health_status': 'vulnerable',
        'notes': 'Jean Reinhardt (23 January 1910 – 16 May 1953), known by his stage name Django Reinhardt, was a Belgian-born Romani-French jazz guitarist and composer. He was the first jazz talent to emerge from Europe and remains the most significant.',
        'schedule': {
            'status': 'active',
            'number_of_adults': 1,
            'number_of_children': 1,
            'allergies': '',
            'diabetic': False,
            'gluten_free': True,
            'dairy_free': True,
            'vegetarian': True,
            'vegan': True,
            'halal': False,
            'start_date': '2020-01-01',
            'end_date': '2020-12-31',
            'monday_delivery': True,
            'wednesday_delivery': True,
            'friday_delivery': True,
            'delivery_notes': None
        }
    },
    {
        'active':True,
        'first_name':'Skip',
        'last_name':'James',
        'address1':'12 Chapel Street',
        'address2':'',
        'town':'Edinburgh',
        'postcode':'EH3 4XY',
        'phone':'0131 555 9600',
        'gdpr_consent':'given_by_client',
        'health_status': 'vulnerable',
        'notes': 'Nehemiah Curtis "Skip" James (June 9, 1902 – October 3, 1969) was an American Delta blues singer, guitarist, pianist and songwriter. His guitar playing is noted for its dark, minor-key sound, played in an open D-minor tuning with an intricate fingerpicking technique.',
        'schedule': {
            'status': 'active',
            'number_of_adults': 1,
            'number_of_children': 3,
            'allergies': 'Wheat allergy',
            'diabetic': False,
            'gluten_free': True,
            'dairy_free': False,
            'vegetarian': False,
            'vegan': True,
            'halal': False,
            'start_date': '2020-01-01',
            'end_date': '2020-12-31',
            'monday_delivery': True,
            'wednesday_delivery': True,
            'friday_delivery': True,
            'delivery_notes': None
        }
    },
    {
        'active':True,
        'first_name':'Derek',
        'last_name':'Parfit',
        'address1':'Room 123',
        'address2':'David Hume Tower',
        'address3': 'University of Edinburgh',
        'town':'Edinburgh',
        'postcode':'EH4 5YA',
        'phone':'0131 555 9700',
        'gdpr_consent':'given_by_client',
        'health_status': 'vulnerable',
        'notes': 'Derek Antony Parfit was a British philosopher who specialised in personal identity, rationality, and ethics. He is widely considered one of the most important and influential moral philosophers of the late 20th and early 21st centuries.',
        'schedule': {
            'status': 'active',
            'number_of_adults': 5,
            'number_of_children': 10,
            'allergies': 'Seafood',
            'diabetic': False,
            'gluten_free': False,
            'dairy_free': True,
            'vegetarian': True,
            'vegan': True,
            'halal': False,
            'start_date': '2020-01-01',
            'end_date': '2020-12-31',
            'monday_delivery': True,
            'wednesday_delivery': True,
            'friday_delivery': True,
            'delivery_notes': None
        }
    },
    {
        'active':True,
        'first_name':'Harry',
        'last_name':'Houdini',
        'address1':'Edinburgh Dungeon',
        'address2':'Market Street',
        'town':'Edinburgh',
        'postcode':'EH1 1AA',
        'phone':'0131 555 9800',
        'gdpr_consent':'given_by_client',
        'health_status': 'vulnerable',
        'notes': 'Harry Houdini was a Hungarian-born American illusionist and stunt performer, noted for his sensational escape acts.',
        'schedule': {
            'status': 'active',
            'number_of_adults': 2,
            'number_of_children': 4,
            'allergies': 'Eggs',
            'diabetic': True,
            'gluten_free': False,
            'dairy_free': False,
            'vegetarian': True,
            'vegan': True,
            'halal': False,
            'start_date': '2020-01-01',
            'end_date': '2020-12-31',
            'monday_delivery': True,
            'wednesday_delivery': True,
            'friday_delivery': True,
            'delivery_notes': 'If no answer please leave food by door'
        }
    },
    {
        'active':True,
        'first_name':'Franz',
        'last_name':'Kafka',
        'address1':'The Castle',
        'address2':'Royal Mile',
        'town':'Edinburgh',
        'postcode':'EH20 9QP',
        'phone':'0131 555 9800',
        'gdpr_consent':'given_by_client',
        'health_status': None,
        'notes': 'Franz Kafka was a German-speaking Bohemian novelist and short-story writer, widely regarded as one of the major figures of 20th-century literature. His work fuses elements of realism and the fantastic.',
    },
    {
        'active':True,
        'first_name':'Tom',
        'last_name':'Waits',
        'address1':'Wide Spot in the Road',
        'address2':'Burma Shave',
        'town':'Edinburgh',
        'postcode':'EH21 1FP',
        'phone':'0131 555 9900',
        'gdpr_consent':'given_by_client',
        'health_status': None,
        'notes': 'Tom Waits is an American singer, songwriter, musician, composer, and actor. His lyrics often focus on the underbelly of society and are delivered in his trademark deep, gravelly voice.',
    },
]

'''
import datetime
from client.models import Client
from meals.models import MealsSchedule
from client.seed import clients

for client in clients:
    client_obj = Client(active=client['active'], first_name=client['first_name'], last_name=client['last_name'], address1=client['address1'], address2=client['address2'], town=client['town'], postcode=client['postcode'], phone=client['phone'], gdpr_consent=client['gdpr_consent'], health_status=client['health_status'], notes=client['notes'])
    client_obj.save()
    if 'schedule' in client:
        schedule = client['schedule']
        MealsSchedule(
            client=client_obj,
            status=schedule['status'],
            number_of_adults=schedule['number_of_adults'],
            number_of_children=schedule['number_of_children'],
            allergies=schedule['allergies'],
            diabetic=schedule['diabetic'],
            gluten_free=schedule['gluten_free'],
            dairy_free=schedule['dairy_free'],
            vegetarian=schedule['vegetarian'],
            vegan=schedule['vegan'],
            halal=schedule['halal'],
            start_date=datetime.datetime.strptime(schedule['start_date'], '%Y-%m-%d'),
            end_date=datetime.datetime.strptime(schedule['end_date'], '%Y-%m-%d'),
            monday_delivery=schedule['monday_delivery'],
            wednesday_delivery=schedule['wednesday_delivery'],
            friday_delivery=schedule['friday_delivery'],
            delivery_notes=schedule['delivery_notes']
        ).save()
'''
