# Generated by Django 3.1.1 on 2021-03-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0004_auto_20210204_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=80)),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('attenders', models.ManyToManyField(blank=True, related_name='attended_foodservice_sessions', to='client.Client')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='foodservice.group')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='GroupBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_adults', models.PositiveSmallIntegerField()),
                ('number_of_children', models.PositiveSmallIntegerField()),
                ('allergies', models.TextField(blank=True, max_length=100, null=True)),
                ('diabetic', models.BooleanField()),
                ('gluten_free', models.BooleanField()),
                ('dairy_free', models.BooleanField()),
                ('vegetarian', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('halal', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foodservice_bookings', to='client.client')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foodservice_bookings', to='foodservice.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='foodservice.grouptype'),
        ),
    ]
