# Generated by Django 3.1.1 on 2021-03-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbooking',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='foodservice.group'),
        ),
    ]
