# Generated by Django 3.1.1 on 2021-03-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0002_auto_20210313_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbooking',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
