# Generated by Django 3.0.5 on 2020-05-23 17:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('address3', models.CharField(blank=True, max_length=250, null=True)),
                ('town', models.CharField(max_length=250)),
                ('postcode', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=30, null=True)),
                ('health_status', models.CharField(blank=True, choices=[('self-isolating', 'Self-isolating'), ('vulnerable', 'Vulnerable'), ('shielding', 'Shielding')], max_length=20, null=True)),
                ('gdpr_consent', models.CharField(blank=True, choices=[('given_by_client', 'Given by client'), ('given_on_behalf', 'Given on behalf of client')], max_length=15, null=True)),
                ('gdpr_consent_giver', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman'), ('intersex', 'Intersex'), ('non-binary', 'Non-binary'), ('other', 'Other')], max_length=10, null=True)),
                ('gender_specify', models.CharField(blank=True, max_length=30, null=True)),
                ('has_disability', models.BooleanField(default=False)),
                ('physical_impairment', models.BooleanField(default=False)),
                ('sensory_impairment', models.BooleanField(default=False)),
                ('mental_health_condition', models.BooleanField(default=False)),
                ('learning_disability', models.BooleanField(default=False)),
                ('hiv_cancer_ms', models.BooleanField(default=False)),
                ('ethnicity_category', models.CharField(blank=True, choices=[('white', 'White'), ('asian', 'Asian, Asian-Scottish or Asian-British'), ('african', 'African, Caribbean or Black'), ('mixed', 'Mixed or Multiple Ethnic Groups'), ('other', 'Other Ethnic Group')], max_length=10, null=True)),
                ('ethnicity_white', models.CharField(blank=True, choices=[('scottish', 'Scottish'), ('english', 'English'), ('irish', 'Irish'), ('northern_irish', 'Northern Irish'), ('british', 'British'), ('gypsy_traveller', 'Gypsy/Traveller'), ('polish', 'Polish'), ('other', 'Other')], max_length=20, null=True)),
                ('ethnicity_asian', models.CharField(blank=True, choices=[('pakistani', 'Pakistani, Pakistani Scottish or Pakistani British'), ('indian', 'Indian, Indian Scottish or Indian British'), ('bangladeshi', 'Bangladeshi, Bangladeshi Scottish or Bangladeshi British'), ('chinese', 'Chinese, Chinese Scottish or Chinese British'), ('other', 'Other')], max_length=20, null=True)),
                ('ethnicity_african', models.CharField(blank=True, choices=[('african', 'African, African Scottish or African British'), ('caribbean', 'Caribbean, Caribbean Scottish or Caribbean British'), ('other', 'Other')], max_length=20, null=True)),
                ('ethnicity_other', models.CharField(blank=True, choices=[('arab', 'Arab, Arab Scottish or Arab British'), ('other', 'Other')], max_length=20, null=True)),
                ('ethnicity_specify', models.CharField(blank=True, max_length=30, null=True)),
                ('has_caring_responsibilities', models.BooleanField(default=False)),
                ('primary_carer_child', models.BooleanField(default=False)),
                ('primary_carer_disabled_child', models.BooleanField(default=False)),
                ('primary_carer_disabled_adult', models.BooleanField(default=False)),
                ('primary_carer_older_person', models.BooleanField(default=False)),
                ('secondary_carer', models.BooleanField(default=False)),
                ('married', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('sexual_orientation', models.CharField(blank=True, choices=[('heterosexual', 'Heterosexual'), ('lesbian', 'Gay woman/lesbian'), ('gay', 'Gay man'), ('bisexual', 'Bisexual'), ('other', 'Other')], max_length=12, null=True)),
                ('sexual_orientation_specify', models.CharField(blank=True, max_length=30, null=True)),
                ('religion', models.CharField(blank=True, choices=[('none', 'No religion or belief'), ('buddhist', 'Buddhist'), ('christian', 'Christian'), ('hindu', 'Hindu'), ('jewish', 'Jewish'), ('muslim', 'Muslim'), ('sikh', 'Sikh'), ('other', 'Other')], max_length=10, null=True)),
                ('religion_specify', models.CharField(blank=True, max_length=30, null=True)),
                ('immigration_status', models.CharField(blank=True, choices=[('uk_resident', 'UK Resident'), ('migrant_worker', 'Migrant Worker'), ('asylum_seeker', 'Asylum Seeker'), ('refugee', 'Refugee')], max_length=14, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
                'unique_together': {('first_name', 'last_name', 'address1', 'postcode')},
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_to', models.CharField(choices=[('dmac', 'DMAC'), ('nw_food_bank', 'NW Food Bank'), ('gha', 'GHA'), ('social_work', 'Social Work'), ('g13_g14_hub', 'G13/G14 Hub'), ('carers_centre', 'Carers Centre'), ('wesrec', 'WESREC'), ('other', 'Other')], max_length=30)),
                ('referred_to_other', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='client.Client')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
