# Generated by Django 3.1.1 on 2021-09-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_casenote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casenote',
            options={'ordering': ('-date',)},
        ),
    ]
