# Generated by Django 3.1.1 on 2021-09-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200707_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_commencing', models.DateField()),
                ('monday_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tuesday_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('wednesday_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('thursday_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('friday_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('saturday_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='staff.staff')),
            ],
            options={
                'ordering': ('week_commencing',),
            },
        ),
    ]
