# Generated by Django 3.1.1 on 2021-09-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='week_commencing',
            field=models.DateField(blank=True, null=True),
        ),
    ]
