# Generated by Django 3.1.1 on 2021-09-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20210903_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='week_commencing',
            field=models.DateField(),
        ),
    ]
