# Generated by Django 3.1.1 on 2021-09-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20210903_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='role',
            field=models.CharField(choices=[('volunteer_driver', 'Volunteer Driver'), ('volunteer_call_handler', 'Volunteer Call Handler'), ('volunteer_other', 'Volunteer Other'), ('board_member', 'Board Member'), ('session_worker', 'Session Worker'), ('play_worker', 'Play Worker')], default='board_member', max_length=30),
            preserve_default=False,
        ),
    ]
