# Generated by Django 3.1.1 on 2021-10-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_timesheet_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='monday_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='week_commencing',
            field=models.DateField(blank=True),
        ),
    ]
