# Generated by Django 3.0.5 on 2020-05-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('time', models.CharField(choices=[('13:00', '13:00 - 13:15'), ('13:15', '13:15 - 13:30'), ('13:30', '13:30 - 13:45'), ('13:45', '13:45 - 14:00'), ('14:00', '14:00 - 14:15')], max_length=5)),
                ('number_of_adults', models.PositiveSmallIntegerField()),
                ('number_of_children', models.PositiveSmallIntegerField()),
                ('allergies', models.TextField(blank=True, max_length=100, null=True)),
                ('diabetic', models.BooleanField()),
                ('gluten_free', models.BooleanField()),
                ('dairy_free', models.BooleanField()),
                ('vegetarian', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='halal_shopping_schedule', to='client.Client')),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='MissedCollectionDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_collection_dates', to='halalshopping.ShoppingSchedule')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='ExceptionDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_dates', to='halalshopping.ShoppingSchedule')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('scheduled', 'Scheduled'), ('ad-hoc', 'Ad-hoc')], default='scheduled', max_length=9)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('13:00', '13:00 - 13:15'), ('13:15', '13:15 - 13:30'), ('13:30', '13:30 - 13:45'), ('13:45', '13:45 - 14:00'), ('14:00', '14:00 - 14:15')], max_length=5)),
                ('number_of_adults', models.PositiveSmallIntegerField()),
                ('number_of_children', models.PositiveSmallIntegerField()),
                ('dietary_requirements', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_collections', to='client.Client')),
            ],
            options={
                'verbose_name_plural': 'Shopping collections',
                'ordering': ('date',),
                'unique_together': {('client', 'date')},
            },
        ),
    ]
