# Generated by Django 3.0.5 on 2020-09-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('creche_capacity', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('attenders', models.ManyToManyField(related_name='attended_sessions', to='client.Client')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='group.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creche_spaces', models.PositiveSmallIntegerField(default=0)),
                ('names_of_children', models.CharField(blank=True, max_length=250, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='client.Client')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='group.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='group.GroupType'),
        ),
    ]
