# Generated by Django 3.1.1 on 2020-09-04 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_email'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsession',
            name='time',
            field=models.TimeField(default=datetime.time(14, 8, 51, 359158)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupsession',
            name='attenders',
            field=models.ManyToManyField(blank=True, related_name='attended_sessions', to='client.Client'),
        ),
        migrations.AlterField(
            model_name='groupsession',
            name='date',
            field=models.DateField(),
        ),
    ]
