# Generated by Django 3.1.1 on 2020-09-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20200904_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsession',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='group.group'),
        ),
    ]
