# Generated by Django 3.1.1 on 2020-09-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20200907_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('start_date',)},
        ),
        migrations.AlterModelOptions(
            name='groupsession',
            options={'ordering': ('date',)},
        ),
    ]
