# Generated by Django 3.1.1 on 2020-11-06 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodhubCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_adults', models.PositiveSmallIntegerField()),
                ('number_of_children', models.PositiveSmallIntegerField()),
                ('allergies', models.TextField(blank=True, max_length=100, null=True)),
                ('diabetic', models.BooleanField()),
                ('gluten_free', models.BooleanField()),
                ('dairy_free', models.BooleanField()),
                ('vegetarian', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foodhub_collections', to='client.client')),
            ],
            options={
                'verbose_name_plural': 'Food Hub collections',
                'ordering': ('date',),
                'unique_together': {('client', 'date')},
            },
        ),
    ]
