# Generated by Django 3.0.5 on 2020-07-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonecalls', '0002_missedcalldate_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonecallNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonecall_notes', to='phonecalls.PhonecallSchedule')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
