# Generated by Django 3.0.5 on 2020-07-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonecalls', '0003_phonecallnotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonecallnotes',
            options={'ordering': ('-date',)},
        ),
    ]
