# Generated by Django 3.1.1 on 2020-09-09 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodbankReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodbank_referrals', to='client.client')),
            ],
            options={
                'ordering': ('date', 'client'),
            },
        ),
    ]
