# Generated by Django 3.1.1 on 2020-11-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodbankreferral',
            options={'ordering': ('-date', 'client')},
        ),
    ]
