# Generated by Django 3.0.5 on 2020-08-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_to_client', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('school', models.CharField(blank=True, max_length=250, null=True)),
                ('school_class', models.CharField(blank=True, max_length=20, null=True)),
                ('activities_consent', models.BooleanField(default=False)),
                ('photography_consent', models.BooleanField(default=False)),
                ('is_peer_volunteer', models.BooleanField(default=False)),
                ('languages_spoken', models.TextField(blank=True, null=True)),
                ('has_no_disability', models.BooleanField(default=False)),
                ('has_physical_impairment', models.BooleanField(default=False)),
                ('has_sensory_impairment', models.BooleanField(default=False)),
                ('has_learning_disability', models.BooleanField(default=False)),
                ('has_mental_health_condition', models.BooleanField(default=False)),
                ('has_any_other_disability', models.BooleanField(default=False)),
                ('disability_details', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='client.Client')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
                'unique_together': {('first_name', 'last_name', 'date_of_birth')},
            },
        ),
    ]
