# Generated by Django 3.0.5 on 2020-09-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name_plural': 'children'},
        ),
    ]
